#  docker-compose -f docker-compose.yml config check validate config
#  ก่อนเรียก   export UID_GID="$(id -u):$(id -g)"
version: "3.1"
services:
  code-server:
    image: "codercom/code-server:latest"
    container_name: code-server
    restart: "always"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - /yourprojectpath/:/home/coder/project
      - $PWD/.config:/home/coder/.config
      - $PWD/code-server:/home/coder/.local/share/code-server
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      com.docker.compose.project: "code-server"
      virtual.host: "vscode1.yourdomain.com"
      virtual.tls-email: your@email.com
      virtual.port: "8080"
    environment:
      - "DOCKER_USER=${USER}"
    user: ${UID_GID}
    
networks:
    default:
        external:
            name: proxy-network
