#  docker-compose -f docker-compose.yml config check validate config
version: "3"
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000"
    user: root
    env_file:
      - .env
    command: start
    restart: always
    volumes:
      - surreal-data:/db/:rw
    labels:
      com.docker.compose.project: "surrealdb"
      virtual.host: "yourdomain.com"
      virtual.tls-email: your@email.com
      virtual.port: "8000"
    environment:
      TZ: Asia/Bangkok
    logging:
      driver: "json-file" # ใช้ json-file driver (default)
      options:
        max-size: "10m"   # จำกัดขนาดของแต่ละไฟล์ log ไม่ให้เกิน 10MB
        max-file: "5"     # เก็บไฟล์ log ไว้สูงสุด 5 ไฟล์      

volumes:
  surreal-data:

networks:
  default:
    external: true
    name: proxy-network
