services:
  ftp-server:
    image: garethflowers/ftp-server
    container_name: my-ftp-server
    ports:
      - "20-21:20-21/tcp"
      - "40000-40009:40000-40009/tcp"
    labels:
      - "virtual.host=ftp.yourdomain.com" # your domain
      - "virtual.port=21" # exposed port of this container
      - "virtual.tls-email=your@email.com" # ssl is now on
    environment:
      - FTP_PASS=Your@Pa$$w0rd
      - FTP_USER=ftpuser
      - TZ=Asia/Bangkok
    volumes:
      - "ftpserver-data:/home/user"
    logging:
      driver: "json-file" # ใช้ json-file driver (default)
      options:
        max-size: "10m"   # จำกัดขนาดของแต่ละไฟล์ log ไม่ให้เกิน 10MB
        max-file: "5"     # เก็บไฟล์ log ไว้สูงสุด 5 ไฟล์      

volumes:
  ftpserver-data:

networks:
  default:
    external: true
    name: proxy-network
