version: "2.1"
services:
  caddy-whoami:
    image: "jwilder/whoami"
    ontainer_name: caddy-whoami
    labels:
      - "virtual.host=your_website.com"
      - "virtual.tls-email=your@email.com" # ssl is now on
      - "virtual.port=8000" # exposed port of this container
    environment:
      VIRTUAL_HOST: "your_website.com"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "your_website.com"
      LETSENCRYPT_EMAIL: "your@email.com"       
      
networks:
  default:
    external:
      name: proxy-network
