
services:
  gitea-pg:
    image: docker.gitea.com/gitea:1.27.3
    container_name: gitea-pg
    # ports:
    #   - "3000:3000"
    #   - "222:22"    
    restart: always
    labels:
      com.docker.compose.project: "gitea"
      virtual.host: "gitea.local.com"
      virtual.tls-email: your@email.com
      virtual.port: "3000"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db-pg:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - TZ=Asia/Bangkok
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    depends_on:
      - db-pg

  db-pg:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
      - TZ=Asia/Bangkok
    volumes:
      - postgres-data:/var/lib/postgresql/data      

volumes:    
  postgres-data:
    driver: local
  gitea-data:
    driver: local

networks:
  default:
    external: true
    name: proxy-network