version: "3"

volumes:
  kcmysql_data:
    driver: local

services:
  kcmysqldb:
    image: mysql:8.0
    volumes:
      - kcmysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak@password
    ports:
      # - 3306:3306
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"     
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    labels:
      - "virtual.host=sso.yourdomain.com" # your domain
      - "virtual.port=8080" # exposed port of this container
      - "virtual.tls-email=your@email.com" # ssl is now on
    environment:
      TZ: Asia/Bangkok
      # for Nginx reverse proxy
      VIRTUAL_HOST: "sso.yourdomain.com"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "sso.yourdomain.com"
      LETSENCRYPT_EMAIL: "your@email.com"
      # for Keycloak setup
      KC_HOSTNAME: sso.yourdomain.com
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HOSTNAME_URL: https://sso.yourdomain.com
      KC_PROXY_HEADERS: xforwarded                                         
      # for Keycloak admin setup      
      KC_BOOTSTRAP_ADMIN: admin                                            
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak@password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak@password
      # for Keycloak metrics and health checks
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
      # keycloak database setup
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://kcmysqldb:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak@password
    command: start-dev
    ports:
      # - 8080:8080
      # - 9000:9000
    depends_on:
      - kcmysqldb
    volumes:
      - kcmysql_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"     

networks:
  default:
    external: true
    name: proxy-network
    driver: bridge


# สร้าง user
# opt/keycloak/bin
# bash-5.1$ ./kc.sh bootstrap-admin user