version: "3"
services:
  cronicle:
    image: soulteary/cronicle:0.9.39
    restart: always
    hostname: cronicle
    ports:
      - 3012:3012
    labels:
      com.docker.compose.project: "yourservicname"
      virtual.host: "cron.yourdomain.com"
      virtual.tls-email: your@email.com
      virtual.port: "3012"
    volumes:
      - cronjob-localtime:/etc/localtime:ro
      - cronjob-timezone:/etc/timezone:ro
      - cronjob-data:/opt/cronicle/data
      - cronjob-logs:/opt/cronicle/logs
      - cronjob-plugins:/opt/cronicle/plugins
    extra_hosts:
      - "cronicle.lab.io:0.0.0.0"
    environment:
      TZ: "Asia/Bangkok"
      VIRTUAL_HOST: "cron.yourdomain.com"
      VIRTUAL_PORT: "3012"
      LETSENCRYPT_HOST: "cron.yourdomain.com"
      LETSENCRYPT_EMAIL: your@email.com

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1",
        ]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  cronjob-localtime:
  cronjob-timezone:
  cronjob-data:
  cronjob-logs:
  cronjob-plugins:

networks:
  default:
    external: true
      name: proxy-network
