version: "3.5"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: "your_git.com"
    restart: unless-stopped
    labels:
      - "virtual.host=your_git.com" # your domain
      - "virtual.port=80" # exposed port of this container
      - "virtual.tls-email=your@email.com" # ssl is now on
    environment:
      VIRTUAL_HOST: "your_git.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "your_git.com"
      LETSENCRYPT_EMAIL: "your@email.com"
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8001:80"
      - "8822:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
    networks:
      - proxy-network

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network

networks:
  default:
    external: true
    name: proxy-network
