version: "3.8"
services:
  nginxweb:
    image: "yourdockeracc/docker-nginxfpm-fw74"
    container_name: nginxwebdev
    working_dir: /var/www/html
    restart: "no"
    # for swoole if use nginx commnt  command
    # command: "/usr/local/bin/php /var/www/html/swoole.php"
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    labels:
      - "virtual.host=your_website.com" # your domain
      - "virtual.port=80" # exposed port of this container
      - "virtual.tls-email=your@email.com" # ssl is now on
    environment:
      VIRTUAL_HOST: "your_website.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "your_website.com"
      LETSENCRYPT_EMAIL: "your@email.com"
    network_mode: "bridge"

networks:
  default:
    external: true
    name: proxy-network
