# docker-compose.yml
version: '3.8'

services:
  php83-caddy:
    image: caddy:latest
    ports:
      - "8080:8080"
    working_dir: /var/www/html
    labels:
      com.docker.compose.project: "phpcaddy"
      virtual.host: "phpcaddy.local.com"
      virtual.tls-email: your@email.com
      virtual.port: "8080"
    environment:
      VIRTUAL_HOST: "phpcaddy.local.com"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "phpcaddy.local.com"
      LETSENCRYPT_EMAIL: your@email.com
      TZ: Asia/Bangkok
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./php:/var/www/
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    restart: unless-stopped

  php:
    build: .
    working_dir: /var/www/html
    volumes:
      - ./php:/var/www
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped

  # ถ้ามีการ update composer.json ให้ run composer-init
  # docker-compose run --rm composer-init
  composer-init:
    image: composer:2
    volumes:
      - ./php:/var/www
    working_dir: /var/www
    command: >
      sh -c "
        composer install --no-dev --optimize-autoloader;
        # if [ ! -d 'vendor' ] && [ -f 'composer.json' ]; then
        #   echo 'Running composer install...';
        #   composer install --no-dev --optimize-autoloader;
        # else
        #   echo 'Composer already installed or no composer.json found.';
        # fi
      "
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    external: true
    name: proxy-network  