scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus:9090
          - node-exporter:9100
          - pushgateway:9091
          - cadvisor:8080

  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets:
          - <dockerserverip>:9323

  - job_name: caddy
    scrape_interval: 5s
    static_configs:
      - targets:
          - caddy-gen-proxy:2015
