#  docker-compose -f docker-compose.yml config check validate config
version: "3.1"
services:
  mongodb2:
    image: "mongo"
    container_name: mongodb2
    restart: "always"
    ports:
      - "27017-27019:27017-27019"
    expose:
      - "27017-27019"
    volumes:
      - ./mongo-volume:/data/db
    labels:
      com.docker.compose.project: "mongodbforexpress"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=dbuser"
      - "MONGO_INITDB_ROOT_PASSWORD=dbpass"

  mongo-express:
    image: "mongo-express"
    container_name: mongo-express
    restart: "always"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    labels:
      - "com.docker.compose.project=mongo-express"
      - "virtual.host=mongoexpress.yourdomain.com"
      - "virtual.tls-email=your@email.com"
      - "virtual.port=8081"
    environment:
      VIRTUAL_HOST: "mongoexpress.yourdomain.com"
      VIRTUAL_PORT: "8081"
      LETSENCRYPT_HOST: "mongoexpress.yourdomain.comm"
      LETSENCRYPT_EMAIL: "your@email.com"     
      ME_CONFIG_MONGODB_ADMINUSERNAME: "dbuser"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "dbpass"

networks:
   default:
     external:
       name: proxy-network
