version: "2.1"

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    logging:
      driver: "json-file" # ใช้ json-file driver (default)
      options:
        max-size: "10m"   # จำกัดขนาดของแต่ละไฟล์ log ไม่ให้เกิน 10MB
        max-file: "5"     # เก็บไฟล์ log ไว้สูงสุด 5 ไฟล์      

networks:
  default:
    external: true
    name: proxy-network
