version: "2.1"

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

networks:
  default:
    external:
      name: nginx-network
