version: "2.1"
services:
  your_website.com:
    image: "abiosoft/caddy:no-stats"
    container_name: your_website.com
    # ports:
      # - "2015:2015"
    labels:
      - "virtual.host=your_website.com"
      - "virtual.tls-email=your@email.com" # ssl is now on
      - "virtual.port=2015" # exposed port of this container
    volumes:
      - ./dist:/srv      
networks:
  default:
    external:
      name: proxy-network
