version: "2.1"
services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    labels:
      - "virtual.host=your_website.com"
      - "virtual.tls-email=your@email.com" # ssl is now on
      - "virtual.port=4873" # exposed port of this container
    environment:
      VIRTUAL_HOST: "your_website.com"
      VIRTUAL_PORT: "4873"
      LETSENCRYPT_HOST: "your_website.com"
      LETSENCRYPT_EMAIL: "your@email.com"
    ports:
      - 4873:4873
    volumes:
      - ./verdaccio:/verdaccio/storage

networks:
  default:
    external: true
    name: proxy-network
