version: "3"
services:
  phpweb:
    image: "webhippie/php-caddy:latest"
    container_name: phpweb
    ports:
      - "8080:8080"
    labels:
      - "virtual.host=your_website.com"
      - "virtual.tls-email=your@email.com" # ssl is now on
      - "virtual.port=8080" # exposed port of this container
    environment:
      VIRTUAL_HOST: "your_website.com"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "your_website.com"
      LETSENCRYPT_EMAIL: "your@email.com"
      ACME_AGREE: true
      TZ: Asia/Bangkok
    volumes:
      - ./php:/srv
      - caddycerts-data:/etc/caddycerts
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  caddycerts-data:

networks:
  default:
    external: true
    name: proxy-network
