version: "3"
services:
  phpweb: 
    image: "abiosoft/caddy:php"
    container_name: phpweb
    ports:
      - "80:80"
      - "443:443"
      - "2105:2015"
    labels:
      - "virtual.host=your_website.com"
      - "virtual.tls-email=your@email.com" # ssl is now on
      - "virtual.port=8000" # exposed port of this container
    environment:
      VIRTUAL_HOST: "your_website.com"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "your_website.com"
      LETSENCRYPT_EMAIL: "your@email.com"   
      ACME_AGREE: true

    volumes:
      - ./php:/srv
      - caddycerts-data:/etc/caddycerts
volumes:
  caddycerts-data:

networks:
  default:
    external:
      name: proxy-network
