version: "3"

services:
  minio:
    build: .
    volumes:
      - ./data:/data
    ports:
      - 9002:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_BROWSER_REDIRECT_URL=http://yourip:9001
      - MINIO_SERVER_URL=http://yourip:9002

networks:
  default:
    external: true
    name: proxy-network
