version: "3.7"

services:
  mysqldb:
    container_name: mysql8
    image: mysql:8.0.36
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: your-default-database
    logging:
      driver: "json-file" # ใช้ json-file driver (default)
      options:
        max-size: "10m"   # จำกัดขนาดของแต่ละไฟล์ log ไม่ให้เกิน 10MB
        max-file: "5"     # เก็บไฟล์ log ไว้สูงสุด 5 ไฟล์      
    ports:
      - "3306:3306"
    expose:
      - "3306"

networks:
  default:
    external:
      name: proxy-network
